version: '2'
services:
  docker-teamster:
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - >
        DOCKER_TEAMSTER_CONFIG={
          "watch": [],
          "ignore": [],
          "usePolling": false,
          restartAwait: 100,
          "bindings": {

          }
        }
